//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnvanterOtomasyonu.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class SanalSunucu
    {
        public int SanalSunucuID { get; set; }
        public string SunucuAdi { get; set; }
        public string KullanımAmacı { get; set; }
        public string IpAdresi { get; set; }
    }
}
