//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnvanterOtomasyonu.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Yazicilar
    {
        public int YaziciID { get; set; }
        public string YaziciMarkaModel { get; set; }
        public string IpAdresi { get; set; }
        public string YaziciBirim { get; set; }
    }
}
